name: "CI"
run-name: ${{ github.actor }} runs TSC Check 🍅
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: TypeScript Check
        id: tsc
        continue-on-error: true
        run: npx tsc --noEmit
      - name: add error label
        # conclusionは、continue-on-error: true を適用しているためにsuccess になる。そのため、outcomeとfailure() でエラーを検知する
        if: ${{ github.event_name == 'pull_request' && failure() && steps.tsc.outcome == 'failure' }}
        uses: actions/github-script@v4
        with:
          # プルリクエストにエラーのラベルを付ける
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['bug']
            })
      - name: check for errors
        if: ${{ steps.tsc.outcome == 'failure' }}
        run: exit 1
          